name: pega_ransom
description: PegaRansom Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^13.6.0
  path_provider: ^2.1.2
  dart:io:
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/pegasom.jpg
